spring:
  jpa:
    database: oracle
    show-sql: true
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.1.1.30:1521:DBTEST
    username: CRPDTA
    password: P1qaz#EDC
#
swagger:
  enable=true
